### ISSUE TITLE
What is the license for this repository?

### ISSUE THREAD

**Issue by anton-matosov** [evaera/Roblox-FFlag-Watcher#5]
Hi @evaera,

This FFlag tool looks amazing! Great job! 
I would to use some pieces of it in my project, however there is no license specified in the repository.

Can you update repository with the license file under which code is redistributed, please?

**Comment by evaera** [comment]
Thanks for pointing that out, just an oversight! I've added the MIT license to the project. I'm curious, is your project open source?

**Comment by anton-matosov** [comment]
Thanks eryn. Unfortunately my project is not open source at the moment.
