### ISSUE TITLE
website not loading

### ISSUE THREAD

**Issue by Trolto** [evaera/Roblox-FFlag-Watcher#73]
Its just stuck like this
![image](https://user-images.githubusercontent.com/70472724/139692939-57e46598-da85-4c02-b09f-6b2deb75c085.png)

**Comment by LoganDark** [comment]
Yes, the website and server seem **extremely** slow now. When it doesn't return a 504 error.

**Comment by LoganDark** [comment]
Looks like it's functioning again (for the moment)
